### ISSUE TITLE
ETB support

### ISSUE THREAD

**Issue by mreis1** [Psychopoulet/split-frames#27]
According to the protocol, certain commands might be returned in multiple blocks. 
Those are then delimited by ETB being ETX used to delimit the latest block.

```
-----ENQ ------>
<----ACK --------

STX -- DATA -- DLE ETB LRC --->
<---------- ACK ----------------

STX -- DATA -- DLE ETB LRC --->
<---------- ACK ----------------

STX -- DATA -- DLE ETX LRC --->
<---------- ACK ----------------

----------- EOT ---------------->
```

ETB 0x17

The ETB management is necessary for messages of more than 248 bytes. The maximum message size (blocks concatenation) is 1024 bytes.

**Comment by Psychopoulet** [comment]
this package is only designed to compile full-filled frame, I don't think I'm able to add some half-filled frame with checkpoints like that
